// resources/js/components/ui/Label.vue
<script setup lang="ts">
import {cn} from '@/lib/utils';
import {type HTMLAttributes} from 'vue';

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()

</script>

<template>
  <label
      data-slot="label"
      :class="cn(
        'flex items-center text-beige-500 font-bold text-xs mb-2',
        'group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50',
        'peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        props.class,
      )"
  >
    <slot/>
  </label>
</template>

// resources/js/components/ui/label.tsx
import * as LabelPrimitive from '@radix-ui/react-label';
import * as React from 'react';

import { cn } from '@/lib/utils';

function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "leading-none select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50 text-xs font-bold text-grey-500",
        className
      )}
      {...props}
    />
  )
}

export { Label }
