// resources/js/components/UserInfo.vue
<script setup lang="ts">
import {useInitials} from '@/composables/useInitials';
import type {User} from '@/types';
import {computed} from 'vue';
import AvatarImage from "@/components/ui/AvatarImage.vue";
import Avatar from "@/components/ui/Avatar.vue";
import AvatarFallback from "@/components/ui/AvatarFallback.vue";

interface Props {
  user: User;
  showEmail?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  showEmail: false,
});

const {getInitials} = useInitials();

// Compute whether we should show the avatar image
const showAvatar = computed(() => props.user.avatar && props.user.avatar !== '');
</script>

<template>
  <Avatar class="h-8 w-8 overflow-hidden rounded-lg">
    <AvatarImage v-if="showAvatar" :src="user.avatar!" :alt="user.name"/>
    <AvatarFallback class="rounded-lg text-white">
      {{ getInitials(user.name) }}
    </AvatarFallback>
  </Avatar>

  <div class="grid flex-1 text-left text-sm leading-tight">
    <span class="truncate font-medium">{{ user.name }}</span>
    <span v-if="showEmail" class="truncate text-xs text-muted-foreground">{{ user.email }}</span>
  </div>
</template>

// resources/js/components/user-info.tsx
import Avatar from '@/components/avatar';
import { User } from '@/types';
import { CaretUpDownIcon } from '@phosphor-icons/react';
import { clsx } from 'clsx';

type UserInfoProps = {
  user: User;
  isSidebarOpen?: boolean;
  className?: string;
};
export default function UserInfo({ user, isSidebarOpen }: UserInfoProps) {
  return (
    <div className="px-4 text-sm">
      <div className="flex cursor-pointer items-center gap-3 p-2 hover:rounded-md hover:bg-grey-300/10 hover:shadow-lg">
        <Avatar
          src={user.avatar}
          alt={user.name}
          fallback={user.name}
          className="font-semibold"
        />
        <div
          className={clsx('flex w-full items-center justify-between', {
            'w-auto opacity-100': isSidebarOpen,
            'w-0 overflow-hidden opacity-0': !isSidebarOpen,
          })}
        >
          <div className="flex flex-col">
            <span className="truncate font-medium">{user.name}</span>
            <span className="truncate text-xs text-grey-300">{user.email}</span>
          </div>
          <CaretUpDownIcon size={18} weight="fill" />
        </div>
      </div>
    </div>
  );
}
