// resources/js/layouts/app-layout.tsx
import Sidebar from '@/components/sidebar';
import { dashboard } from '@/routes';
import {
  ArrowsDownUpIcon,
  ChartDonutIcon,
  GearIcon,
  HouseIcon,
  SidebarSimpleIcon,
  TipJarIcon,
} from '@phosphor-icons/react';
import { clsx } from 'clsx';
import React from 'react';

const navbarItems = [
  {
    name: 'Overview',
    href: dashboard().url,
    icon: HouseIcon,
  },
  {
    name: 'Transactions',
    href: '#',
    icon: ArrowsDownUpIcon,
  },
  {
    name: 'Budgets',
    href: '#',
    icon: ChartDonutIcon,
  },
  {
    name: 'Pots',
    href: '#',
    icon: TipJarIcon,
  },
  {
    name: 'Settings',
    href: '#',
    icon: GearIcon,
  },
];
interface AppLayoutProps {
  title: string;
  children: React.ReactNode;
}

export default function AppLayout({ title, children }: AppLayoutProps) {
  const [isSidebarOpen, setIsSidebarOpen] = React.useState(true);

  const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen);

  return (
    <div
      className={clsx(
        'grid h-screen grid-cols-1 grid-rows-[64px_1fr_52px] gap-1 bg-beige-100 transition-all duration-300 ease-in-out md:grid-rows-[64px_1fr_74px] lg:grid-rows-[64px_1fr] lg:pr-4',
        {
          'lg:grid-cols-[300px_1fr]': isSidebarOpen,
          'lg:grid-cols-[88px_1fr]': !isSidebarOpen,
        },
      )}
    >
      <Sidebar isSidebarOpen={isSidebarOpen} navbarItems={navbarItems} />

      {/* Header - arriba siempre */}
      <header className="order-1 flex items-center gap-4 p-4 text-3xl font-bold md:order-2">
        <button
          className="hidden text-grey-900 lg:block"
          onClick={toggleSidebar}
        >
          <SidebarSimpleIcon size={24} weight="fill" />
        </button>
        <h1 className="text-3xl text-grey-900">{title}</h1>
      </header>

      {/* Main Content - medio en mobile, derecha en desktop */}
      <main className="order-2 mx-4 overflow-auto rounded-xl bg-white p-4 shadow md:mb-4 lg:order-3">
        {children}
      </main>
    </div>
  );
}

// resources/js/layouts/AppLayout.vue
<script setup lang="ts">
import BottomNav from "@/components/BottomNav.vue";
import Sidebar from "@/components/Sidebar.vue";
import {dashboard} from "@/routes";
import UserInfo from "@/components/UserInfo.vue";
import {usePage} from "@inertiajs/vue3";
import PhosphorIcon from "@/components/ui/PhosphorIcon.vue";
import AccountDropdown from "@/components/AccountDropdown.vue";
import {ref} from "vue";

interface Props {
  title?: string;
}

const routes = [
  {
    name: 'Overview',
    href: dashboard().url,
    icon: 'house',
  },
  {
    name: 'Transactions',
    href: "#",
    icon: 'ArrowsDownUp',
  },
  {
    name: 'Budgets',
    href: '#',
    icon: 'ChartDonut',
  },
  {
    name: 'Pots',
    href: '#',
    icon: 'TipJar',
  },
  {
    name: 'Recurring bills',
    href: '#',
    icon: 'receipt',
  }
]

const props = defineProps<Props>()
const user = usePage().props.auth.user;
const isOpen = ref(false);

function toggleDropdown() {
  isOpen.value = !isOpen.value;
}

</script>

<template>
  <div
      class="grid grid-cols-1 grid-rows-[auto_1fr_auto] h-screen bg-beige-100 lg:grid-cols-[250px_1fr] lg:grid-rows-[auto_1fr]">

    <aside class="hidden lg:block bg-grey-900 rounded-br-2xl rounded-tr-2xl lg:row-start-1 lg:row-end-3">
      <sidebar :routes="routes"/>
    </aside>

    <header
        class="flex justify-between items-center bg-grey-900 text-white lg:bg-beige-100 lg:text-grey-900 px-4 py-2 lg:col-start-2 ">
      <h1 class="font-bold text-[32px]">{{ props.title }}</h1>
      <div class="relative">
        <div class="flex items-center gap-2 lg:hidden" @click="toggleDropdown">
          <user-info :user="user"/>
          <PhosphorIcon name="CaretUpDown" :size="18" weight="regular"/>
        </div>
        <AccountDropdown :isOpen="isOpen"/>
      </div>
    </header>

    <main class="overflow-auto p-4 lg:col-start-2">
      <slot/>
    </main>

    <footer class=" flex justify-center items-end px-2 bg-grey-900 rounded-tl-xl rounded-tr-xl lg:hidden min-h-[52px] ">
      <bottom-nav :routes="routes"/>
    </footer>
  </div>
</template>
