// resources/js/pages/Auth/Login.vue
<script lang="ts" setup>
import { Form, Link } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import {
    Field,
    FieldError,
    FieldGroup,
    FieldLabel,
    FieldSet,
} from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import AuthLayout from '@/layout/AuthLayout.vue';
import { register } from '@/routes';
import { store } from '@/routes/login';
</script>

<template>
    <AuthLayout>
        <div
            class="w-full space-y-8 rounded-2xl bg-white px-5 py-6 md:max-w-140"
        >
            <h1 class="font-preset-1">Login</h1>
            <div>
                <Form
                    v-slot="{ processing, errors }"
                    :reset-on-error="['password']"
                    :reset-on-success="['password']"
                    class="space-y-8"
                    v-bind="store.form()"
                >
                    <FieldGroup>
                        <Field>
                            <label
                                class="font-preset-5-bold text-grey-500"
                                for="email"
                                >Email</label
                            >
                            <Input
                                id="email"
                                autocomplete="email"
                                autofocus
                                class="py-3"
                                name="email"
                                required
                                tabindex="1"
                                type="email"
                            />
                        </Field>
                        <FieldError v-if="errors.email">{{
                            errors.email
                        }}</FieldError>
                        <FieldSet class="gap-1">
                            <Field>
                                <label
                                    class="font-preset-5-bold text-grey-500"
                                    for="password"
                                >
                                    Password
                                </label>
                                <Input
                                    id="password"
                                    name="password"
                                    required
                                    tabindex="2"
                                    type="password"
                                />
                            </Field>
                            <Field orientation="horizontal">
                                <FieldLabel for="remember"
                                    >Remember me</FieldLabel
                                >
                                <Checkbox
                                    id="remember"
                                    name="remember"
                                    tabindex="3"
                                />
                            </Field>
                            <FieldError v-if="errors.password">{{
                                errors.password
                            }}</FieldError>
                        </FieldSet>
                    </FieldGroup>

                    <Button
                        :disabled="processing"
                        class="w-full bg-grey-900"
                        size="xl"
                        type="submit"
                    >
                        Login
                    </Button>
                </Form>
            </div>
            <p class="text-center font-preset-4 text-grey-500">
                Need to create an account?
                <Link
                    :href="register()"
                    class="font-preset-4-bold text-grey-900 underline"
                    >Sign Up</Link
                >
            </p>
        </div>
    </AuthLayout>
</template>

// resources/js/pages/auth/login.tsx
import { Form, Head } from '@inertiajs/react';
import InputError from '@/components/input-error';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Spinner } from '@/components/ui/spinner';
import AuthLayout from '@/layouts/auth-layout';
import { register } from '@/routes';
import { store } from '@/routes/login';
import { request } from '@/routes/password';

type Props = {
  status?: string;
  canResetPassword: boolean;
  canRegister: boolean;
};

export default function Login({
  status,
  canResetPassword,
  canRegister,
}: Props) {
  return (
    <AuthLayout>
      <Head title="Log in" />

      <Form
        {...store.form()}
        resetOnSuccess={['password']}
        className="flex w-full flex-col gap-6 rounded-lg bg-white px-5 py-6 md:w-lg"
      >
        {({ processing, errors }) => (
          <>
            <h2 className="text-3xl font-bold">Login</h2>

            <div className="grid gap-6">
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  name="email"
                  required
                  autoFocus
                  tabIndex={1}
                  autoComplete="email"
                  placeholder="email@example.com"
                />
                <InputError message={errors.email} />
              </div>

              <div className="grid gap-2">
                <div className="flex items-center">
                  <Label
                    htmlFor="password"
                    className="text-xs font-bold text-grey-500"
                  >
                    Password
                  </Label>
                  {canResetPassword && (
                    <TextLink
                      href={request()}
                      className="ml-auto text-xs text-grey-500"
                      tabIndex={5}
                    >
                      Forgot password?
                    </TextLink>
                  )}
                </div>
                <Input
                  id="password"
                  type="password"
                  name="password"
                  required
                  tabIndex={2}
                  autoComplete="current-password"
                  placeholder="Password"
                />
                <InputError message={errors.password} />
              </div>

              <div className="flex items-center space-x-3">
                <Checkbox id="remember" name="remember" tabIndex={3} />
                <Label htmlFor="remember" className="text-xs text-grey-500">
                  Remember me
                </Label>
              </div>

              <Button
                type="submit"
                className="mt-4 w-full"
                size="xl"
                tabIndex={4}
                disabled={processing}
                data-test="login-button"
              >
                {processing && <Spinner />}
                Log in
              </Button>
            </div>

            {canRegister && (
              <div className="text-center text-sm text-muted-foreground">
                Need to create an account?{' '}
                <TextLink href={register()} tabIndex={5}>
                  Sign up
                </TextLink>
              </div>
            )}
          </>
        )}
      </Form>

      {status && (
        <div className="mb-4 text-center text-sm font-medium text-green-600">
          {status}
        </div>
      )}
    </AuthLayout>
  );
}
