// resources/js/pages/Auth/Login.tsx
import AuthLayout from "@/layouts/auth-layout";
import {Form, Head, Link} from "@inertiajs/react";
import {store} from "@/routes/login";
import Label from "@/components/ui/Label";
import Input from "@/components/ui/Input";
import InputError from "@/components/input-error";
import Spinner from "@/components/ui/Spinner";
import {register} from "@/routes";

export default function Login({}) {
  return (
    <AuthLayout title="Login">

      <Head title="Logi"/>

      <Form {...store.form()}
            resetOnSuccess={['password']}
            resetOnError={['password']}
            className="flex flex-col gap-6"
      >
        {({errors, processing}) => (
          <>
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                required
                autoFocus
                tabIndex={1}
                autoComplete="email"
                name="email"
              />
              <InputError message={errors.email} className="mt-2"/>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                required
                autoFocus
                tabIndex={1}
                autoComplete="password"
                name="password"
              />
              <InputError message={errors.email} className="mt-2"/>
            </div>

            <button
              disabled={processing}
              className="bg-grey-900 flex items-center justify-center gap-2 text-white font-bold text-sm rounded-md p-4 cursor-pointer"
            >
              {processing && <Spinner/>}
              Login
            </button>

            <div className="flex items-center justify-center gap-2">
              <span className="text-sm text-beige-500">Need to create an account?</span>
              <Link href={register()} className="underline font-bold text-sm">Sign Up</Link>
            </div>
          </>
        )}
      </Form>
    </AuthLayout>
  )
}

// resources/js/pages/Auth/Login.vue
<script lang="ts" setup>
import { Form, Link } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import {
    Field,
    FieldError,
    FieldGroup,
    FieldLabel,
    FieldSet,
} from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import AuthLayout from '@/layout/AuthLayout.vue';
import { register } from '@/routes';
import { store } from '@/routes/login';
</script>

<template>
    <AuthLayout>
        <div
            class="w-full space-y-8 rounded-2xl bg-white px-5 py-6 md:max-w-140"
        >
            <h1 class="font-preset-1">Login</h1>
            <div>
                <Form
                    v-slot="{ processing, errors }"
                    :reset-on-error="['password']"
                    :reset-on-success="['password']"
                    class="space-y-8"
                    v-bind="store.form()"
                >
                    <FieldGroup>
                        <Field>
                            <label
                                class="font-preset-5-bold text-grey-500"
                                for="email"
                                >Email</label
                            >
                            <Input
                                id="email"
                                autocomplete="email"
                                autofocus
                                class="py-3"
                                name="email"
                                required
                                tabindex="1"
                                type="email"
                            />
                        </Field>
                        <FieldError v-if="errors.email">{{
                            errors.email
                        }}</FieldError>
                        <FieldSet class="gap-1">
                            <Field>
                                <label
                                    class="font-preset-5-bold text-grey-500"
                                    for="password"
                                >
                                    Password
                                </label>
                                <Input
                                    id="password"
                                    name="password"
                                    required
                                    tabindex="2"
                                    type="password"
                                />
                            </Field>
                            <Field orientation="horizontal">
                                <FieldLabel for="remember"
                                    >Remember me</FieldLabel
                                >
                                <Checkbox
                                    id="remember"
                                    name="remember"
                                    tabindex="3"
                                />
                            </Field>
                            <FieldError v-if="errors.password">{{
                                errors.password
                            }}</FieldError>
                        </FieldSet>
                    </FieldGroup>

                    <Button
                        :disabled="processing"
                        class="w-full bg-grey-900"
                        size="xl"
                        type="submit"
                    >
                        Login
                    </Button>
                </Form>
            </div>
            <p class="text-center font-preset-4 text-grey-500">
                Need to create an account?
                <Link
                    :href="register()"
                    class="font-preset-4-bold text-grey-900 underline"
                    >Sign Up</Link
                >
            </p>
        </div>
    </AuthLayout>
</template>
