// resources/js/pages/Auth/Register.vue
<script setup lang="ts">
import GuestLayout from "@/layouts/GuestLayout.vue";
import {Form, Link} from "@inertiajs/vue3";
import Input from "@/components/ui/Input.vue";
import Label from "@/components/ui/Label.vue";
import Button from "@/components/ui/Button.vue";
import {login} from "@/routes";
import InputError from "@/components/InputError.vue";
import RegisteredUserController from "@/actions/Laravel/Fortify/Http/Controllers/RegisteredUserController";
import {PhCircleNotch} from "@phosphor-icons/vue";
</script>

<template>
  <GuestLayout title="Register">
    <Form
        v-bind="RegisteredUserController.store.form()"
        :reset-on-error="['password', 'password_confirmation']"
        v-slot="{ errors, processing }"
        class="flex flex-col gap-2 w-full"
    >
      <div>
        <Label for="name">Name</Label>
        <Input
            id="name"
            type="text"
            name="name"
            required
            autofocus
            autocomplete="name"
            :tabindex="1"
        />
        <input-error :message="errors.name"/>
      </div>
      <div>
        <Label for="email">Email</Label>
        <Input id="email" type="email" name="email" required autocomplete="email" :tabindex="2"/>
        <input-error :message="errors.email"/>
      </div>
      <div>
        <Label for="password">Password</Label>
        <Input id="password" type="password" name="password" required autocomplete="new-password" :tabindex="3"/>
        <input-error :message="errors.password"/>
      </div>
      <div>
        <Label for="password_confirmation">Confirm Password</Label>
        <Input id="password_confirmation" type="password" name="password_confirmation" required
               autocomplete="new-password" :tabindex="4"/>
      </div>

      <Button type="submit" class="mt-4" :disabled="processing">
        <PhCircleNotch :size="32" v-if="processing" class="h-4 w-4 animate-spin"/>
        Create Account
      </Button>

      <div class="flex items-center justify-center gap-2 mt-4">
          <span class="text-sm text-grey-500">
            Already have an account?
          </span>
        <Link :href="login()"
              class="underline underline-offset-4 text-sm font-bold transition-colors duration-300 ease-out hover:text-beige-500!">
          Login
        </Link>
      </div>
    </Form>
  </GuestLayout>
</template>

// resources/js/pages/Auth/Register.tsx
import AuthLayout from "@/layouts/auth-layout";
import {Form, Link} from "@inertiajs/react";
import {store} from "@/routes/register";
import Label from "@/components/ui/Label";
import Input from "@/components/ui/Input";
import InputError from "@/components/input-error";
import Spinner from "@/components/ui/Spinner";
import {login} from "@/routes";

export default function Register() {
  return (
    <AuthLayout>
      <h1 className="font-bold text-3xl mb-6 leading-1.2">Sign Up</h1>
      <Form {...store.form()}
            resetOnSuccess={['password', 'password_confirmation']}
            resetOnError={['password', 'password_confirmation']}
            disableWhileProcessing

      >
        {({errors, processing}) => (
          <>
            <div className="grid gap-6">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input
                  id="name"
                  type="text"
                  required
                  autoFocus
                  tabIndex={1}
                  autoComplete="name"
                  name="name"
                  placeholder="Full Name"
                />
                <InputError message={errors.name} className="mt-2"/>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  required
                  tabIndex={2}
                  autoComplete="email"
                  name="email"
                  placeholder="jdoe@finance.com"
                />
                <InputError message={errors.email} className="mt-2"/>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  required
                  tabIndex={3}
                  name="password"
                  placeholder="Password"
                />
                <InputError message={errors.password} className="mt-2"/>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="password_confirmation">Password Confirmation</Label>
                <Input
                  id="password_confirmation"
                  type="password"
                  required
                  tabIndex={4}
                  name="password_confirmation"
                  placeholder="Confirm Password"
                />
                <InputError message={errors.password_confirmation} className="mt-2"/>
              </div>

              <button className="bg-grey-900 text-white font-bold text-sm rounded-md p-4 cursor-pointer">
                {processing && <Spinner/>}
                Create Account
              </button>

              <div className="flex items-center justify-center gap-2">
                <span className="text-sm text-beige-500">Already have an account?</span>
                <Link href={login()} className="underline font-bold text-sm">Login</Link>
              </div>

            </div>
          </>
        )}


      </Form>
    </AuthLayout>
  )
}
