// resources/js/pages/auth/register.tsx
import { Form, Head } from '@inertiajs/react';
import InputError from '@/components/input-error';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Spinner } from '@/components/ui/spinner';
import AuthLayout from '@/layouts/auth-layout';
import { login } from '@/routes';
import { store } from '@/routes/register';

export default function Register() {
  return (
    <AuthLayout>
      <Head title="Register" />

      <Form
        {...store.form()}
        resetOnSuccess={['password', 'password_confirmation']}
        resetOnError={['password', 'password_confirmation']}
        disableWhileProcessing
        className="w-full space-y-8 rounded-xl bg-white px-5 py-6 md:w-lg"
        data-test="register-form"
      >
        {({ processing, errors }) => (
          <>
            <h2 className="text-3xl font-bold">Sign Up</h2>
            <div className="grid gap-6">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input
                  id="name"
                  type="text"
                  required
                  autoFocus
                  tabIndex={1}
                  autoComplete="name"
                  name="name"
                  placeholder="Full name"
                />
                <InputError message={errors.name} className="mt-2" />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="email">Email address</Label>
                <Input
                  id="email"
                  type="email"
                  required
                  tabIndex={2}
                  autoComplete="email"
                  name="email"
                  placeholder="email@example.com"
                />
                <InputError message={errors.email} />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  required
                  tabIndex={3}
                  autoComplete="new-password"
                  name="password"
                  placeholder="Password"
                />
                <InputError message={errors.password} />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="password_confirmation">Confirm password</Label>
                <Input
                  id="password_confirmation"
                  type="password"
                  required
                  tabIndex={4}
                  autoComplete="new-password"
                  name="password_confirmation"
                  placeholder="Confirm password"
                />
                <InputError message={errors.password_confirmation} />
              </div>

              <Button
                type="submit"
                className="mt-2 w-full"
                size="xl"
                tabIndex={5}
                data-test="register-user-button"
              >
                {processing && <Spinner />}
                Create account
              </Button>
            </div>

            <div className="text-center text-sm text-muted-foreground">
              Already have an account?{' '}
              <TextLink href={login()} tabIndex={6}>
                Log in
              </TextLink>
            </div>
          </>
        )}
      </Form>
    </AuthLayout>
  );
}

// resources/js/pages/Auth/Register.vue
<script lang="ts" setup>
import { Form, Link } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button';
import {
    Field,
    FieldDescription,
    FieldError,
    FieldGroup,
    FieldLabel,
    FieldSet,
} from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import AuthLayout from '@/layout/AuthLayout.vue';
import { login } from '@/routes';
import { store } from '@/routes/register';
</script>

<template>
    <AuthLayout>
        <div
            class="w-full space-y-8 rounded-2xl bg-white px-5 py-6 md:max-w-140"
        >
            <h1 class="font-preset-1">Sign Up</h1>
            <div>
                <Form
                    v-slot="{ errors, processing }"
                    :reset-on-error="['password']"
                    :reset-on-success="['password']"
                    class="space-y-8"
                    v-bind="store.form()"
                >
                    <FieldGroup>
                        <Field>
                            <FieldLabel
                                class="font-preset-5-bold text-grey-500"
                                for="name"
                                >Name</FieldLabel
                            >
                            <Input
                                id="name"
                                autofocus
                                name="name"
                                required
                                tabindex="1"
                                type="text"
                            />
                        </Field>
                        <Field>
                            <label
                                class="font-preset-5-bold text-grey-500"
                                for="email"
                                >Email</label
                            >
                            <Input
                                id="email"
                                autocomplete="email"
                                autofocus
                                class="py-3"
                                name="email"
                                required
                                tabindex="2"
                                type="email"
                            />
                        </Field>
                        <FieldError v-if="errors.email">{{
                            errors.email
                        }}</FieldError>
                        <FieldSet class="gap-1">
                            <Field>
                                <FieldLabel
                                    class="font-preset-5-bold text-grey-500"
                                    for="password"
                                    >Create Password</FieldLabel
                                >
                                <Input
                                    id="password"
                                    name="password"
                                    required
                                    tabindex="3"
                                    type="password"
                                />
                            </Field>
                            <FieldDescription align="end">
                                Password must be at least 8 characters.
                            </FieldDescription>

                            <FieldError v-if="errors.password">{{
                                errors.password
                            }}</FieldError>
                        </FieldSet>
                    </FieldGroup>

                    <Button
                        :disabled="processing"
                        class="w-full bg-grey-900"
                        size="xl"
                        tabindex="4"
                        type="submit"
                    >
                        Create Account
                    </Button>
                </Form>
            </div>
            <p class="text-center font-preset-4 text-grey-500">
                Already have an account?
                <Link
                    :href="login()"
                    class="font-preset-4-bold text-grey-900 underline"
                    >Login</Link
                >
            </p>
        </div>
    </AuthLayout>
</template>
